Feature/author view
matiasvenditti/bookin-front pull request #17
Opened 2020-09-04 22:20 UTC by pepemaluza

# Description

Please include a summary of the change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How has this been tested?

Please describe the tests that you ran to verify your changes.

- [ ] Automation testing (Unit or integration tests)
- [x ] Manual testing (Postman)

# Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x ] My pull request is up to date with develop

2020-09-05 00:48 UTC, pepemaluza commented on src/scenes/main/Author/Author.tsx
> +        if (!isAdmin)
No tiene que estar negado.

2020-09-05 01:28 UTC, matiasvenditti commented on src/services/AuthorService.ts
> +    return instance.post<Author>(`${baseURL}/authors/${authorID}`, config)
No funciona el GET, esto debería ser: 
return instance.post<Author>(`${baseURL}/authors/${**authorID.id**}`, config)

2020-09-05 01:29 UTC, matiasvenditti commented on src/services/AuthorService.ts
> +    const config: AxiosRequestConfig = {
No hace falta pasarle esta config porque el content type de la request es json (application/json), y es el default para axios, asi que no haría falta.

2020-09-05 01:31 UTC, matiasvenditti commented on src/services/AuthorService.ts
> +    return instance.post<Author>(`${baseURL}/authors/${authorID}`, config)
Debería ser **instance.get**

2020-09-06 12:27 UTC, matiasvenditti commented on src/scenes/main/Author/Author.tsx
> +                    <Typography align='center'> <Loader /> </Typography>
Aca le tuve que poner a Typography `variant='subtitle1'` para sacar un error de la consola

2020-09-06 12:28 UTC, matiasvenditti commented on src/scenes/main/Author/Author.tsx
> +                <AppBar position='static'>
AppBar no hace falta ponerlo porque se agrega en Router siempre

2020-09-06 12:28 UTC, matiasvenditti commented on src/scenes/main/Author/Author.tsx
> +                </AppBar>
AppBar no va

2020-09-06 12:34 UTC, matiasvenditti commented on src/scenes/main/Author/Author.tsx
> +                <div className='card-container'>
Para que esto te quede mas parecido a lo que es el wireframe yo le cambiaria la clase del `main.css` en la linea 8.

```
.route-container .card-container {
    width: 100%;
    box-sizing: border-box;
    padding: 20px 65px 15px;
    margin-top: 20px;
    /* background-color: #dddddd; */
}
```

2020-09-06 12:36 UTC, matiasvenditti requested changes
Dejo dos cambios simples

1. En Author.tsx es un fix de un error en la terminal + sacar el AppBar que no hace falta
2. En main.css un fix de estilos

2020-09-06 19:19 UTC, matiasvenditti approved these changes

2020-09-06 19:22 UTC, merged